name: auto assign

on:
  workflow_call:
    inputs:
      repo_token:
        description: 'GITHUB_TOKEN'
        required: true
        type: string

jobs:
  add-reviews:
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v2.0.0
        with:
          repo-token: ${{ inputs.repo_token }}
