name: tests

on:
  workflow_call:
    inputs:
      os_version:
        required: true
        type: string
        default: ubuntu-latest
      python_version:
        required: true
        type: string
        default: "3.12"
      integration:
        required: false
        type: string
        default: "false"
      end_to_end:
        required: false
        type: string
        default: "false"
    secrets:
      GH_TOKEN:
        required: false

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  tests:
    runs-on: ${{ inputs.os_version }}
    steps:
    - name: Checkout
      uses: actions/checkout@main
    - name: Set up Python ${{ inputs.python_version }}
      uses: actions/setup-python@main
      with:
        python-version: ${{ inputs.python_version }}
    - name: Preview GitHub Token
      run: echo $GH_TOKEN | sha256sum | cut -c 1-10
    - name: Set up PDM
      uses: pdm-project/setup-pdm@main
      with:
        python-version: ${{ inputs.python_version }}
    - name: Install dependencies
      run: pdm sync
    - name: Run unit tests
      run: make test
    - name: Run integration tests
      if: ${{ inputs.integration == 'true' }}
      run: make integration-test
    - name: Run end-to-end tests
      if: ${{ inputs.end_to_end == 'true' }}
      run: make end-to-end-test